### PR TITLE
fix: #84 invalid memory address or nil pointer dereference at getFileSHA()

### LINKED ISSUE #84: bug: invalid memory address or nil pointer dereference at getFileSHA()
## Describe the Bug

invalid memory address or nil pointer dereference at getFileSHA()

```
2021/12/28 13:18:02 language is go-1.17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x12bbfc7e0]

goroutine 1 [running]:
github.com/merico-dev/stream/internal/pkg/githubactions.(*GithubActions).getFileSHA(0x1400006a7e0, {0x12bc03c3c, 0xe})
	github.com/merico-dev/stream/internal/pkg/githubactions/githubactions.go:125 +0x1a0
github.com/merico-dev/stream/internal/pkg/githubactions.(*GithubActions).DeleteWorkflow(0x1400006a7e0, 0x140001c65d0)
	github.com/merico-dev/stream/internal/pkg/githubactions/githubactions.go:80 +0x60
github.com/merico-dev/stream/internal/pkg/githubactions.Uninstall(0x14000113c10)
	github.com/merico-dev/stream/internal/pkg/githubactions/uninstall.go:17 +0x218
github.com/merico-dev/stream/cmd/githubactions.Plugin.Uninstall({0x0, 0x0}, 0x14000113c10)
	github.com/merico-dev/stream/cmd/githubactions/main.go:27 +0x34
github.com/merico-dev/stream/internal/pkg/pluginengine.Uninstall(0x14000113bf0)
	github.com/merico-dev/stream/internal/pkg/pluginengine/plugin.go:42 +0xd4
github.com/merico-dev/stream/internal/pkg/planmanager.(*Plan).Execute(0x14000113b60)
	github.com/merico-dev/stream/internal/pkg/planmanager/plan.go:61 +0x3b0
main.installCMDFunc(0x10348b980, {0x1400006a3e0, 0x0, 0x2})
	github.com/merico-dev/stream/cmd/devstream/install.go:45 +0x318
github.com/spf13/cobra.(*Command).execute(0x10348b980, {0x1400006a3c0, 0x2, 0x2})
	github.com/spf13/cobra@v1.2.1/command.go:860 +0xa04
github.com/spf13/cobra.(*Command).ExecuteC(0x10348bc00)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x7b8
github.com/spf13/cobra.(*Command).Execute(0x10348bc00)
	github.com/spf13/cobra@v1.2.1/command.go:902 +0x30
main.main()
	github.com/merico-dev/stream/cmd/devstream/main.go:28 +0x30
```

image

## Other notes

I've fixed this bug at #74 but it's reopen at #76 by "resolve conflict". 

image

We should pay more attentions at "avoid confict"/"resolve conflict"/"code review"

/kind bug
/cc @merico-dev/devstream to us all.

### PR DESCRIPTION
**Pull request by daniel-hutao**
Signed-off-by: Daniel Hu <tao.hu@merico.dev>

# Summary

fix: invalid memory address or nil pointer dereference at getFileSHA()

### Related Issues

fix #84 

@IronCore864 @lfbdev Please take a review.

### CODE REVIEW

File: internal/pkg/githubactions/githubactions.go [hunk 1]
```diff
@@ -122,14 +122,14 @@ func (ga *GithubActions) getFileSHA(filename string) (string, error) {
...
 
-	if resp.StatusCode == http.StatusNotFound {
-		return "", nil
-	}
-
 	if err != nil {
 		return "", err
 	}
 
+	if resp.StatusCode == http.StatusNotFound {
```
Comment (lfbdev) [inline internal/pkg/githubactions/githubactions.go:129]: should be in front of  line 125， or it will return error while file not found

Comment (daniel-hutao) [reply internal/pkg/githubactions/githubactions.go:132]: done
