### PR TITLE
Fix: `dtm init xxx` created the state file

### LINKED ISSUE #240: devstream.state file created even when "apply" isn't executed.
## Describe the Bug

When we run `dtm init`, `dtm version`, or simply `dtm`, the `devstream.state` file is created.

## Expected Behavior

We should only create the state file when we run `dtm apply`; for other commands like `version`, `init` that don't rely on the state file, we don't need to create the file prematurely.

### PR DESCRIPTION
**Pull request by daniel-hutao**
Signed-off-by: Daniel Hu <tao.hu@merico.dev>

# Summary

Fix: `dtm init xxx` created the state file

## Description

Describe what this PR does and what problems it tries to solve in a few sentences.

### Related Issues

close #240

### CODE REVIEW

File: internal/pkg/backend/backend.go [hunk 1]
```diff
@@ -4,21 +4,12 @@ import (
 	"fmt"
 
 	"github.com/merico-dev/stream/internal/pkg/backend/local"
+	"github.com/merico-dev/stream/pkg/util/log"
 )
 
-type BackendType string
+type Type string
```
Comment (daniel-hutao) [inline internal/pkg/backend/backend.go:10]: the `BackendType` and `BackendLocal` below start with the package name isn't a good name style. Because the users will write the code like: `backend.BackendType` or backend.BackendLocal`. Obviously the `backend.Type & backend.Local` is better.

**Review by lfbdev — APPROVED** [review]

**Review by IronCore864 — APPROVED** [review]
